import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createServer,root} from './serve.mjs';
const modulePath=process.env.UF_PLAYWRIGHT_MODULE;if(!modulePath)throw Error('Set UF_PLAYWRIGHT_MODULE to a local Playwright module');
const {chromium}=await import(modulePath),server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({executablePath:process.env.UF_CHROMIUM_EXECUTABLE,headless:true,args:['--no-sandbox']}),errors=[],external=[],checks=[];
const context=await browser.newContext({viewport:{width:1440,height:1100}});await context.route('**/*',route=>{const url=route.request().url();if(!url.startsWith(base+'/')){external.push(url);return route.abort();}return route.continue();});
const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
async function check(name,fn){await fn();checks.push(name);console.log('PASS '+name);}
async function choose(page,id){await page.locator('#scenario').selectOption(id);assert.equal(await page.locator('#result article').count(),0);await page.locator('#check').click();await page.locator('#result article').waitFor();}
try{
 await check('desktop host and sandboxed iframe',async()=>{await page.goto(base);const f=page.frameLocator('#embed');await f.locator('#scenario').waitFor();assert.equal(await page.locator('#embed').getAttribute('sandbox'),'allow-scripts allow-same-origin');await page.screenshot({path:path.join(root,'desktop.png'),fullPage:true});});
 await check('tenant theme switch and private provenance',async()=>{await page.locator('#tenant').selectOption('nordlicht');const f=page.frameLocator('#embed');await f.locator('#scenario').selectOption('private');await f.locator('#check').click();await f.locator('#result article').waitFor();await f.locator('#result summary').click();assert.match(await f.locator('#result').innerText(),/SYN-nordlicht-PRIVATE/);assert.doesNotMatch(await f.locator('#result').innerText(),/SYN-atelier-PRIVATE/);});
 await page.goto(base+'/embed.html?tenant=atelier');
 await check('all six shared-engine synthetic decisions and safe selection reset',async()=>{for(const [id,state] of [['exact','confirmed'],['revision','unknown'],['excluded','excluded'],['sku','unknown'],['connector','unknown'],['private','confirmed']]){await choose(page,id);assert.equal(await page.locator('#result article').getAttribute('data-outcome'),state);assert.match(await page.locator('#result').innerText(),/SYNTHETISCHE/);}});
 await check('no-result search clears old confirmation',async()=>{await page.locator('#search').fill('<img src=x onerror=alert(1)>');assert.equal(await page.locator('#result article').count(),0);assert.equal(await page.locator('#check').isDisabled(),true);assert.equal(await page.locator('img').count(),0);await page.locator('#search').fill('');});
 await check('keyboard control, source disclosure and no purchase link',async()=>{await page.locator('#scenario').selectOption('exact');await page.locator('#check').focus();await page.keyboard.press('Enter');await page.locator('#result article').waitFor();await page.locator('#result summary').focus();await page.keyboard.press('Enter');assert.match(await page.locator('#result').innerText(),/test-source/);assert.equal(await page.locator('#result a').count(),0);});
 await check('320/375/768 px, readable fallback states and no horizontal overflow',async()=>{for(const width of [320,375,768]){await page.setViewportSize({width,height:900});await choose(page,'revision');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(width===375)await page.screenshot({path:path.join(root,'mobile-unknown.png'),fullPage:true});}await page.setViewportSize({width:375,height:900});await choose(page,'exact');await page.screenshot({path:path.join(root,'mobile-confirmed.png'),fullPage:true});});
 await check('200% text retains result and controls',async()=>{await page.evaluate(()=>document.styleSheets[0].insertRule('p, label, select, input, button, summary, dd, dt, small {font-size:200% !important}',document.styleSheets[0].cssRules.length));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await page.locator('#check').isEnabled(),true);});
 await check('loaded demo operates with network offline',async()=>{await context.setOffline(true);await choose(page,'excluded');assert.equal(await page.locator('#result article').getAttribute('data-outcome'),'excluded');await context.setOffline(false);});
 await check('unknown tenant fails closed without default shop',async()=>{await page.goto(base+'/embed.html?tenant=foreign');assert.match(await page.locator('main').innerText(),/Unbekannter Demo-Mandant/);assert.equal(await page.locator('#scenario').count(),0);});
 await check('cookies/storage/network and script errors',async()=>{assert.deepEqual(await context.cookies(),[]);assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);assert.deepEqual(external,[]);assert.deepEqual(errors,[]);});
 fs.writeFileSync(path.join(root,'browser-evidence.json'),JSON.stringify({checkedAt:new Date().toISOString(),browser:browser.version(),checks,errors,externalRequests:external,limits:['Chromium emulation, not a physical device or screenreader audit.','Offline interaction after initial local load; offline reload and external embed deployment are not supported.','Client fixtures are public synthetic data; this does not demonstrate real server-side tenant secrecy.']},null,2)+'\n');
}finally{await browser.close();await new Promise(r=>server.close(r));}
