import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {createBusinessAdapter,canonicalRequest,createSelectionSession} from './shared-adapter.mjs';
import {inspectOnBothSurfaces} from '../dual-platform-owner-review/bridge.mjs';
import {createAdapter,validateView} from './adapter.mjs';
import {listScenarios} from './fixtures.mjs';
import {createAccessLab,demoPrincipal,demoGrant,authorize,cacheKey,roleScopes} from './access-lab.mjs';
import {root} from './serve.mjs';
const ctx={tenantId:'atelier',caseId:'exact'},row=listScenarios('atelier')[0];
const req={caseId:'exact',asset:row.asset,part:row.part,variantKnown:true};
for(const tenantId of ['atelier','nordlicht'])for(const c of listScenarios(tenantId))test(`shared v1 parity ${tenantId}/${c.id}`,async()=>{
 const request={caseId:c.id,asset:c.asset,part:c.part,variantKnown:true},context={tenantId,caseId:c.id};
 const shared=inspectOnBothSurfaces(canonicalRequest(request,context),{tenantId:'demo-'+tenantId,caseId:'demo-'+c.id});
 const result=await createBusinessAdapter()(request,context);assert.equal(result.ok,true);assert.equal(result.view.outcome,shared.business.outcome);
 assert.equal(shared.engine.testOnly,true);assert.equal(shared.engine.canConfirmFitment,false);assert.equal(shared.engine.canConfirmPurchase,false);
 if(c.id==='private')assert.equal(result.view.evidence[0].tenantId,tenantId);
});
test('missing revision on previously positive case delegates unknown to shared engine',async()=>{const r=await createBusinessAdapter()({...req,variantKnown:false},ctx);assert.equal(r.ok,true);assert.equal(r.view.outcome,'unknown');assert.match(r.view.reason,/REVISION_UNKNOWN/);});
for(const [name,change] of [
 ['schema',d=>{d.engine.schemaVersion='999';}],['asset',d=>{d.engine.assetId='foreign';}],['part',d=>{d.engine.partId='foreign';}],['assembly',d=>{d.engine.assemblyId='foreign';}],['dataVersion',d=>{d.engine.dataVersion='stale';}],
 ['real dataset flag',d=>{d.engine.testOnly=false;}],['fitment permission',d=>{d.engine.canConfirmFitment=true;}],['purchase permission',d=>{d.engine.canConfirmPurchase=true;}],['foreign tenant view',d=>{d.business.tenantId='demo-nordlicht';}],['foreign case view',d=>{d.business.caseId='demo-private';}],
 ['unmapped private field',d=>{d.business.secret='PRIVATE';}],['foreign source id',d=>{d.engine.sourceIds=['foreign'];}],['non-synthetic source',d=>{d.engine.sources[0].kind='manufacturer';}],['non-synthetic source url',d=>{d.engine.sources[0].url='https://real.example/';}],['foreign evidence',d=>{d.business.evidence[0].id='foreign';}],
])test('shared response denies '+name,async()=>{const adapter=createBusinessAdapter({inspect:(r,c)=>{const d=structuredClone(inspectOnBothSurfaces(r,c));change(d);return d;}});assert.equal((await adapter(req,ctx)).ok,false);});
test('unconfirmed engine cannot be upgraded by presentation',async()=>{const adapter=createBusinessAdapter({inspect:(r,c)=>{const d=structuredClone(inspectOnBothSurfaces(r,c));d.business.outcome='confirmed';d.business.evidence=[{id:'test-source',scope:'public',tenantId:null,label:'bad',text:'bad',rights:'synthetic-test-only'}];return d;}});assert.equal((await adapter({...req,variantKnown:false},ctx)).ok,false);});
test('forged SKU and tenant context fail before shared inspection',async()=>{let called=false;const a=createBusinessAdapter({inspect:()=>{called=true;}});assert.equal((await a({...req,part:'OTHER'},ctx)).ok,false);assert.equal((await a(req,{...ctx,tenantId:'foreign'})).ok,false);assert.equal(called,false);});
test('stale delayed positive cannot resurrect after selection invalidation',async()=>{let resolve;const session=createSelectionSession(),p=session.run(()=>new Promise(r=>{resolve=r;}));session.invalidate();resolve({outcome:'confirmed'});assert.deepEqual(await p,{current:false,value:null});});
test('newer request wins when old positive resolves last',async()=>{let resolve;const session=createSelectionSession(),old=session.run(()=>new Promise(r=>{resolve=r;}));assert.deepEqual(await session.run(()=>Promise.resolve({outcome:'unknown'})),{current:true,value:{outcome:'unknown'}});resolve({outcome:'confirmed'});assert.equal((await old).current,false);});
test('in-flight caller mutation cannot change tenant binding',async()=>{let release;const c={...ctx},view=structuredClone(row.response);const a=createAdapter({invoke:()=>new Promise(r=>{release=r;}),validateContract:()=>true,mapToView:r=>r});const pending=a(req,c);await Promise.resolve();c.tenantId='nordlicht';release(view);assert.equal((await pending).view.tenantId,'atelier');});
test('view prototypes and missing fields rejected',()=>{assert.throws(()=>validateView(Object.create(row.response),ctx));const v=structuredClone(row.response);delete v.next;assert.throws(()=>validateView(v,ctx));});
const principal=()=>demoPrincipal('atelier','admin',1000),request=()=>({tenantId:'atelier',action:'fitment:read',usage:'private-test',grant:demoGrant('atelier','tenant',1000)});
for(const [role,action,expected] of [['reader','fitment:read','ALLOWED'],['reader','evidence:read','ROLE_DENIED'],['reader','audit:read','ROLE_DENIED'],['reviewer','evidence:read','ALLOWED'],['reviewer','audit:read','ROLE_DENIED'],['admin','audit:read','ALLOWED']])test(`role ${role} / ${action}`,()=>{assert.equal(authorize(demoPrincipal('atelier',role,1000),{...request(),action},1000),expected);});
for(const [name,edit,expected] of [
 ['cross tenant',(p,r)=>{r.tenantId='nordlicht';},'TENANT_DENIED'],['unknown role',p=>{p.role='superuser';},'ROLE_DENIED'],['unknown action',(p,r)=>{r.action='export:all';},'ROLE_DENIED'],['scope missing',p=>{p.token.scopes=[];},'TOKEN_DENIED'],['foreign token',p=>{p.token.tenantId='nordlicht';},'TOKEN_DENIED'],['expired token',p=>{p.token.expiresAt=1000;},'TOKEN_DENIED'],['revoked token',p=>{p.token.revoked=true;},'TOKEN_DENIED'],['foreign feed',(p,r)=>{r.grant.tenantId='nordlicht';},'FEED_RIGHTS_DENIED'],['unknown rights',(p,r)=>{r.grant.rights='unknown';},'FEED_RIGHTS_DENIED'],['revoked feed',(p,r)=>{r.grant.revoked=true;},'FEED_RIGHTS_DENIED'],['expired feed',(p,r)=>{r.grant.expiresAt=1000;},'FEED_RIGHTS_DENIED'],['real feed',(p,r)=>{r.grant.kind='manufacturer';},'FEED_RIGHTS_DENIED'],['public feed with tenant',(p,r)=>{r.grant.scope='public';},'FEED_RIGHTS_DENIED'],['production usage',(p,r)=>{r.usage='b2b';},'PRODUCTION_DENIED']
])test('access denies '+name,()=>{const p=principal(),r=request();edit(p,r);assert.equal(authorize(p,r,1000),expected);});
test('role scope configuration is immutable',()=>{assert.throws(()=>roleScopes.reader.push('audit:read'));});
test('rate budget per tenant, denied requests do not consume allowed budget, window resets',()=>{let now=1000;const lab=createAccessLab({clock:()=>now,limit:2,windowMs:100});assert.equal(lab.check(principal(),{...request(),tenantId:'nordlicht'}).allowed,false);assert.equal(lab.check(principal(),request()).allowed,true);assert.equal(lab.check(principal(),request()).allowed,true);assert.equal(lab.check(principal(),request()).decision,'RATE_LIMITED');const other=demoPrincipal('nordlicht','admin',now);assert.equal(lab.check(other,{...request(),tenantId:'nordlicht',grant:demoGrant('nordlicht','tenant',now)}).allowed,true);now+=100;assert.equal(lab.check(principal(),request()).allowed,true);});
test('minimal tenant-scoped audit, role denial, bounded retention, clearing and no secret payloads',()=>{let now=1000;const lab=createAccessLab({clock:()=>now,maxEvents:2,retentionMs:100});for(let i=0;i<3;i++)lab.check(principal(),{...request(),query:'SECRET',token:'SECRET'});const rows=lab.audit(principal());assert.equal(rows.length,2);assert.ok(!JSON.stringify(rows).includes('SECRET'));assert.deepEqual(Object.keys(rows[0]),['sequence','at','tenantId','role','action','decision']);assert.equal(lab.audit(demoPrincipal('nordlicht','admin',now)).length,0);assert.throws(()=>lab.audit(demoPrincipal('atelier','reader',now)));now+=100;assert.deepEqual(lab.audit(principal()),[]);lab.clear();assert.deepEqual(lab.audit(principal()),[]);});
test('cache namespace concept covers tenant, role and rights version without collisions',()=>{const a={tenantId:'atelier',role:'reader',grantVersion:'1',contractVersion:'1.0.0',caseId:'private'};assert.notEqual(cacheKey(a),cacheKey({...a,tenantId:'nordlicht'}));assert.notEqual(cacheKey(a),cacheKey({...a,role:'admin'}));assert.notEqual(cacheKey(a),cacheKey({...a,grantVersion:'2'}));assert.notEqual(cacheKey(a),cacheKey({...a,caseId:'private,other'}));});
test('shared source hashes unchanged from assigned integration basis',()=>{const lock=JSON.parse(fs.readFileSync(path.join(root,'shared-source-lock.json')));for(const [f,digest] of Object.entries(lock.files))assert.equal(createHash('sha256').update(fs.readFileSync(path.join(root,'..',f))).digest('hex'),digest);});
