import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {root} from './serve.mjs';
const run=(args)=>{const r=spawnSync(process.execPath,args,{encoding:'utf8',maxBuffer:4e6});if(r.status!==0)throw Error(r.stdout+r.stderr);return r.stdout;};
for(const f of fs.readdirSync(root).filter(f=>f.endsWith('.mjs')))run(['--check',path.join(root,f)]);
const tests=run(['--test',path.join(root,'tests.mjs'),path.join(root,'pilot.test.mjs'),path.join(root,'../fitment-engine-v1-poc/contract.test.mjs'),path.join(root,'../dual-platform-owner-review/bridge.test.mjs')]);if(!/pass 196/.test(tests)||!/fail 0/.test(tests))throw Error('Unexpected test totals');
const files=['index.html','embed.html','style.css','pilot.css','host.mjs','widget.mjs','adapter.mjs','shared-adapter.mjs','access-lab.mjs','fixtures.mjs','serve.mjs'];
const artifacts=Object.fromEntries(files.map(f=>{const b=fs.readFileSync(path.join(root,f));return [f,{bytes:b.length,sha256:createHash('sha256').update(b).digest('hex')}];}));
const sharedSourceLock=JSON.parse(fs.readFileSync(path.join(root,'shared-source-lock.json')));
fs.writeFileSync(path.join(root,'validation.json'),JSON.stringify({checkedAt:new Date().toISOString(),baseCommit:sharedSourceLock.baseCommit,node:process.version,businessTests:95,sharedRegressionTests:101,nodeTests:196,failures:0,syntax:'all local mjs passed',delivery:'direct static files; no build dependencies',artifacts,sharedSourceLock,limits:['Browser suite is separate.','Client access lab is not server IAM or production secrecy.','No actual interviews, prices, API or pilot outcome.']},null,2)+'\n');
console.log('196 Node tests, syntax, shared source lock and SHA256 delivery manifest passed.');
