import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {integrateDysonModels,validateDysonEvidence,sha256} from './import-dyson-models-wave2.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const e=JSON.parse(fs.readFileSync(path.join(root,'integrations/dyson-model-research-wave2.json')));
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'dyson-wave2-test-'));
let rejected=0;
const snapshot=folder=>{
 const files={};const walk=(dir,relative='')=>{for(const ent of fs.readdirSync(dir,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){const file=path.join(dir,ent.name),key=relative+ent.name;if(ent.isDirectory())walk(file,key+'/');else files[key]=ent.isSymbolicLink()?'SYMLINK:'+fs.readlinkSync(file):sha256(fs.readFileSync(file));}};
 walk(folder);return files;
};
const restore=target=>execFileSync('python3',[path.join(root,'integrations/restore-source-checkpoint.py'),'--target',target],{stdio:'pipe'});
try{
 const target=path.join(temp,'first');restore(target);
 const baseline=JSON.parse(fs.readFileSync(path.join(target,'src/data/dyson-pack.js'),'utf8').match(/export const brandPack=(\{[^\n]*\});/)[1]);
 assert.equal(validateDysonEvidence(e,baseline).length,38);
 const accepted=x=>x.candidates.filter(c=>c.status==='accepted');
 const bad=(label,mutate)=>{const altered=structuredClone(e);mutate(altered);assert.throws(()=>validateDysonEvidence(altered,baseline),undefined,label);rejected++;};
 bad('Repeated model',x=>{x.candidates[1]=structuredClone(x.candidates[0]);});
 bad('Existing model code',x=>{accepted(x)[0].modelCode=baseline.models[0].code;});
 bad('Legacy series',x=>{accepted(x)[0].canonicalModel=baseline.models[0].series;});
 bad('Unobserved base identity',x=>{accepted(x)[0].baseIdentity='Dyson:INVENTED';});
 bad('Colour cannot create base',x=>{accepted(x)[0].canonicalModel='Big Ball 2 Gold';});
 bad('Bundle cannot create base',x=>{accepted(x)[0].canonicalModel='Omni-glide+';});
 bad('Deferred identity cannot be imported',x=>{x.candidates.find(c=>c.status==='deferred').status='accepted';});
 bad('Foreign brand',x=>{accepted(x)[0].manufacturer='Bosch';});
 bad('Foreign market',x=>{accepted(x)[0].market='UK';});
 bad('Unobserved regional alias',x=>{accepted(x)[0].regionalVariant='UP15';});
 bad('Scope excludes robot',x=>{accepted(x)[0].formFactor='robot';});
 bad('SKU-like model is not DC model',x=>{accepted(x).find(c=>c.modelCode).modelCode='123456-01';});
 bad('Source is required',x=>{accepted(x)[0].sources=[];});
 bad('Failed retrieval',x=>{accepted(x)[0].sources[0].status='inconclusive';});
 bad('Source title identifies model',x=>{accepted(x)[0].sources[0].observedTitle='Dyson support';});
 bad('Wrong model page',x=>{accepted(x)[0].sources[0].url=accepted(x)[1].sources[0].url;});
 for(const url of ['http://www.dyson.de/support','https://www.dyson.de.evil.example/support','https://user:secret@www.dyson.de/support','https://www.dyson.de:443/support?x=1','https://www.dyson.co.uk/support'])bad('Unqualified source '+url,x=>{accepted(x)[0].sources[0].url=url;});
 bad('Document must be manufacturer-linked',x=>{accepted(x).find(c=>c.sources.length>1).sources[1].linkedFrom='https://www.dyson.de/support';});
 bad('Document host/path cannot be invented',x=>{accepted(x).find(c=>c.sources.length>1).sources[1].url='https://www.dyson.de/unobserved.pdf';});
 bad('Observation date is explicit',x=>{accepted(x)[0].checkedAt='yesterday';});
 bad('Extraction checksum required',x=>{accepted(x)[0].sources[0].sourceExtractSha256='';});
 for(const field of ['price','stock','shipping','ean','productCode','deviceSku','parts','aliases','variants'])bad('No inference of '+field,x=>{accepted(x)[0][field]='invented';});
 bad('No new fitment',x=>{accepted(x)[0].relationships=[{code:'965633-01'}];});
 bad('No new parts',x=>{accepted(x)[0].newParts=1;});
 bad('No false independent total',x=>{x.summary.independentTotal=92;});
 bad('Summary cannot conceal filler',x=>{x.summary.acceptedNewModelReferences=46;});
 bad('No renewed legacy fitment',x=>{x.baseline.partAudit[0].fitmentReapproved=true;});
 bad('Old observations cannot renew counts',x=>{x.baseline.modelAudit[0].newCountDelta=1;});
 bad('Version must match checkpoint',x=>{x.appVersion='1.29.0';});
 bad('Branch restriction is part of evidence',x=>{x.branch='main';});
 bad('At most 46 refs',x=>{const sample=structuredClone(accepted(x)[0]);for(let i=0;i<9;i++)x.candidates.push({...sample,candidateId:'invented-'+i});});
 const original=snapshot(target);
 const failure=(label,run,expected)=>{assert.throws(run,expected,label);assert.deepEqual(snapshot(target),original,'Atomic failure: '+label);rejected++;};
 failure('--check never imports',()=>integrateDysonModels({target,check:true}),/has not been applied/);
 const bin=path.join(temp,'bin');fs.mkdirSync(bin);fs.writeFileSync(path.join(bin,'git'),"#!/bin/sh\nprintf '%s\\n' main\n",{mode:0o755});
 failure('CLI refuses other branch before mutation',()=>execFileSync(process.execPath,[path.join(root,'integrations/import-dyson-models-wave2.mjs'),'--target',target],{env:{...process.env,PATH:bin+path.delimiter+process.env.PATH},stdio:'pipe'}),/Only work\/model-dyson-wave2/);
 const conflict=path.join(target,'src/core/typeplate.js'),old=fs.readFileSync(conflict);
 fs.appendFileSync(conflict,'\n// concurrent edit\n');const alteredSnapshot=snapshot(target);
 assert.throws(()=>integrateDysonModels({target}),/Checkpoint conflict/);assert.deepEqual(snapshot(target),alteredSnapshot);rejected++;fs.writeFileSync(conflict,old);
 failure('Partial staging write',()=>integrateDysonModels({target,transactionFs:{...fs,writeFileSync(){throw Error('Injected write error');}}}),/Injected write error/);
 let renames=0;
 failure('Failed commit rename rolls back',()=>integrateDysonModels({target,transactionFs:{...fs,renameSync(a,b){if(++renames===2)throw Error('Injected rename error');fs.renameSync(a,b);}}}),/Injected rename error/);
 const concurrent=path.join(target,'concurrent-build-note.txt');
 assert.throws(()=>integrateDysonModels({target,transactionFs:{...fs,cpSync(a,b,options){fs.cpSync(a,b,options);fs.writeFileSync(concurrent,'preserve concurrent work');}}}),/Concurrent target conflict/);
 assert.equal(fs.readFileSync(concurrent,'utf8'),'preserve concurrent work');fs.unlinkSync(concurrent);assert.deepEqual(snapshot(target),original);rejected++;
 fs.symlinkSync('src/data/catalog.js',path.join(target,'forbidden-symlink'));
 assert.throws(()=>integrateDysonModels({target}),/Symlink/);rejected++;fs.unlinkSync(path.join(target,'forbidden-symlink'));
 const alias=path.join(temp,'alias');fs.symlinkSync(target,alias,'dir');assert.throws(()=>integrateDysonModels({target:alias}),/Symlink/);rejected++;fs.unlinkSync(alias);
 const collision=path.join(target,'src/data/dyson-models-wave2.js');fs.writeFileSync(collision,'preserve');
 assert.throws(()=>integrateDysonModels({target}),/collision/);assert.equal(fs.readFileSync(collision,'utf8'),'preserve');rejected++;fs.unlinkSync(collision);
 const result=integrateDysonModels({target});assert.equal(result.addedModels,38);assert.equal(result.newParts,0);
 const once=snapshot(target);assert.equal(integrateDysonModels({target}).state,'already-integrated');
 assert.deepEqual(snapshot(target),once,'Idempotent replay');assert.equal(integrateDysonModels({target,check:true}).state,'already-integrated');assert.deepEqual(snapshot(target),once,'Read-only --check');
 const target2=path.join(temp,'second');restore(target2);integrateDysonModels({target:target2});assert.deepEqual(snapshot(target2),once,'Two fresh checkpoints produce byte-identical sources');
 fs.appendFileSync(path.join(target,'src/data/dyson-models-wave2.js'),'\n// preserve this edit');const changed=snapshot(target);
 assert.throws(()=>integrateDysonModels({target}),/Integrated output conflict/);assert.deepEqual(snapshot(target),changed);rejected++;
 console.log(JSON.stringify({passed:true,rejectedInvalidCases:rejected,changedFiles:result.changedFiles.length,freshReplay:'byte-identical',idempotent:true,transactionRollback:true}));
}finally{fs.rmSync(temp,{recursive:true,force:true});}
