import assert from 'node:assert/strict';
import {createMarketplaceHandler} from './marketplace-handler.mjs';
const userId='00000000-0000-4000-8000-000000000001';
const url='https://example.invalid/functions/v1/marketplace-search/access';
let calls=0,received;
const common={authenticate:async()=>({id:userId}),authorizePilot:async id=>{received=id;return true;},reserveQuota:async()=>{calls++;throw Error('must never reserve');},providers:{ebay:{mode:'live',search:async()=>{calls++;}},amazon:{mode:'live',search:async()=>{calls++;}}}};
const handler=createMarketplaceHandler(common);
let response=await handler(new Request(url));assert.equal(response.status,200);assert.equal(received,userId);assert.equal(response.headers.get('cache-control'),'no-store');
assert.deepEqual(await response.json(),{status:'pilot_allowed',pilotAllowed:true,backendVersion:4,providers:{ebay:'access_required',amazon:'access_required'}});
const active=createMarketplaceHandler({...common,env:{MARKETPLACE_LIVE_ENABLED:'true'},providers:{ebay:common.providers.ebay}});
assert.deepEqual((await (await active(new Request(url))).json()).providers,{ebay:'configured',amazon:'access_required'});
const denied=createMarketplaceHandler({...common,authorizePilot:async()=>false});response=await denied(new Request(url));assert.equal(response.status,403);assert.equal((await response.json()).pilotAllowed,false);
const guest=createMarketplaceHandler({...common,authenticate:async()=>null});assert.equal((await guest(new Request(url))).status,401);
const dbDown=createMarketplaceHandler({...common,authorizePilot:async()=>{throw Error('private connection details');}});response=await dbDown(new Request(url));assert.equal(response.status,503);assert.deepEqual(await response.json(),{status:'pilot_unavailable'});
const authDown=createMarketplaceHandler({...common,authenticate:async()=>{throw Error('private details');}});assert.deepEqual(await (await authDown(new Request(url))).json(),{status:'auth_unavailable'});
assert.equal((await handler(new Request(url,{method:'POST'}))).status,405);
assert.equal((await handler(new Request(url+'?user_id=another-user'))).status,400,'arbitrary identities cannot be requested');
assert.equal((await handler(new Request(url,{headers:{origin:'https://attacker.invalid'}}))).status,403);
response=await handler(new Request(url,{headers:{origin:'https://straikerabi.github.io'}}));assert.equal(response.headers.get('access-control-allow-origin'),'https://straikerabi.github.io');
assert.equal((await handler(new Request(url,{method:'OPTIONS',headers:{origin:'https://straikerabi.github.io'}}))).status,204);
assert.equal(calls,0,'status checks consume no quota and call no provider');
console.log('Access-status checks passed: own verified identity, independent pilot/provider gates, read-only/no quota, CORS, cache exclusion and closed failures. Synthetic requests only.');
