import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {integrateParts,validatePartsEvidence,effectiveHoover,snapshot,sha256} from './import-parts-fitment-wave3-oem.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const evidencePath=path.join(root,'integrations/parts-fitment-wave3-evidence.json');
const baselinePath=path.join(root,'integrations/parts-fitment-wave3-baseline.json');
const e=JSON.parse(fs.readFileSync(evidencePath));
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'parts-fitment-wave3-test-'));
const restore=target=>execFileSync('python3',[path.join(root,'integrations/restore-source-checkpoint.py'),'--target',target],{stdio:'pipe'});
const raw=(target,brand)=>JSON.parse(fs.readFileSync(path.join(target,'src/data/'+brand.toLowerCase()+'-pack.js'),'utf8').match(/export const brandPack=(\{[^\n]*\});/)[1]);
const refresh=x=>{for(const s of x.sources){const {observationSha256,...facts}=s;s.observationSha256=sha256(JSON.stringify(facts));}};
let negative=0;
try{
 const target=path.join(temp,'first');restore(target);
 const packs={Samsung:raw(target,'Samsung'),Hoover:effectiveHoover(raw(target,'Hoover'))};
 assert.equal(validatePartsEvidence(e,packs).articles.size,21);
 const bad=(label,mutate)=>{const altered=structuredClone(e);mutate(altered);refresh(altered);assert.throws(()=>validatePartsEvidence(altered,packs),undefined,label);negative++;};
 const samsung=x=>x.fitments.find(f=>f.brand==='Samsung'),hoover=x=>x.fitments.find(f=>f.brand==='Hoover');
 bad('Duplicate OEM/region SKU',x=>x.articles.push(structuredClone(x.articles[0])));
 bad('Duplicate exact relationship',x=>x.fitments.push(structuredClone(x.fitments[0])));
 bad('Duplicate source identity',x=>x.sources.push(structuredClone(x.sources[0])));
 bad('Missing article source',x=>x.articles[0].identitySourceId='unobserved');
 bad('Missing fitment source',x=>samsung(x).sourceId='unobserved');
 bad('Wrong battery despite same family',x=>{samsung(x).partCode='VCA-SBTC97/GL';});
 bad('Unsuffixed article is not the /VT SKU',x=>{samsung(x).partCode='VCA-SPW95/VT';samsung(x).sourceId='samsung-model:VS90F40EEK/WD';});
 bad('Different Samsung model in the family',x=>{samsung(x).modelCode='VS70H28HFC';});
 bad('EEM alias is not EEK',x=>{const f=samsung(x);f.modelCode='VS90F40EEK';f.reference='VS90F40EEM/WD';f.sourceId='samsung-model:VS90F40EEM/WD';});
 bad('Samsung wrong /WA country execution',x=>{const f=samsung(x);f.reference=f.reference.replace('/WD','/WA');});
 bad('Unknown Samsung suffix',x=>{samsung(x).reference='VS70H28HEK/AA';});
 bad('Hoover wrong product code',x=>{hoover(x).productCode='39401038';});
 bad('Hoover family model with other code',x=>{hoover(x).modelCode='HF201H011';});
 bad('GB catalogue cannot prove DE',x=>{hoover(x).region='DE';});
 bad('GB article cannot become DE offer',x=>{x.articles.find(a=>a.brand==='Hoover').region='DE';});
 bad('No broad serial approval',x=>{hoover(x).serialScope='all';});
 bad('Serial condition is required',x=>{hoover(x).conditions=hoover(x).conditions.filter(c=>!c.includes('Serien-'));});
 bad('Clean Station requirement retained',x=>{x.fitments.find(f=>f.partCode==='VCA-ADB952').conditions=['Die Herstellerliste wurde zu diesem Modell geprüft.'];});
 bad('Sweeper attachment requirement retained',x=>{x.fitments.find(f=>f.partCode==='VCA-SPW95').conditions=['Die Herstellerliste wurde zu diesem Modell geprüft.'];});
 bad('Different article OEM source',x=>{x.articles[0].code=x.articles[1].code;});
 bad('Unknown article fitment',x=>{hoover(x).partCode='99999999';});
 bad('Shop PID is not OEM article number',x=>{x.sources.find(s=>s.kind==='hoover-article').oemCode='3052564OH';});
 bad('Not genuine',x=>{x.sources.find(s=>s.kind==='hoover-article').genuine=false;});
 bad('Catalogue membership missing',x=>{x.sources.find(s=>s.id===hoover(x).sourceId).partListings=[];});
 bad('General heading even if URL names model',x=>{x.sources.find(s=>s.id===hoover(x).sourceId).title='Hoover Vacuum Cleaner (Floorcare): 1 - 12 of 9706';});
 bad('Wrong model code in catalogue URL',x=>{const s=x.sources.find(s=>s.id===hoover(x).sourceId);s.url=s.url.replace(s.productCode,'39401038');});
 bad('Aftermarket excluded from this original intake',x=>{x.articles[0].partTypeId='other';});
 bad('Forged EAN',x=>{x.articles[0].ean='1234567890123';});
 bad('null EAN is not string null',x=>{x.articles.find(a=>a.ean===null).ean='null';});
 bad('EAN cannot come from another source',x=>{x.articles[0].ean=x.articles[1].ean;});
 bad('Missing date',x=>{x.sources[0].checkedAt=null;});
 bad('Unobserved future date',x=>{x.sources[0].checkedAt='2026-12-31';});
 bad('Failed source retrieval',x=>{x.sources[0].httpStatus=403;});
 bad('Missing body digest',x=>{x.sources[0].bodySha256='';});
 for(const url of ['http://www.samsung.com/de/x','https://www.samsung.com.evil.example/de/x','https://user:secret@www.samsung.com/de/x','https://www.samsung.com/us/home-appliance-accessories/x','https://www.samsung.com/de/x?tracking=1'])bad('Unqualified source '+url,x=>{x.sources[0].url=url;});
 for(const field of ['price','stock','shipping','availability','offers','sourceQuote','deviceQuote'])bad('No commercial inference '+field,x=>{x.articles[0][field]='fabricated';});
 bad('No unobserved material number',x=>{x.articles[0].materialNumber='12345678';});
 bad('No invented replacement identifier in drawing',x=>{x.sources.find(s=>s.kind==='manufacturer-linked-drawing').oemCodes=['20'];});
 bad('Deferred item cannot be counted accepted',x=>{x.deferred[0].status='accepted';});
 bad('Checkpoint version fixed',x=>{x.appVersion='1.30.0';});
 bad('Exclusive branch required',x=>{x.branch='main';});
 const initial=snapshot(target);
 const freshCheck=integrateParts({target,check:true});assert.equal(freshCheck.state,'validated-not-integrated');assert.deepEqual(snapshot(target),initial,'--check never mutates a fresh target');
 const failure=(label,run,pattern)=>{assert.throws(run,pattern,label);assert.deepEqual(snapshot(target),initial,'Atomic failure: '+label);negative++;};
 failure('Filesystem root cannot be an intake target',()=>integrateParts({target:path.parse(target).root}),/Filesystem root/);
 failure('Repository root cannot be an intake target',()=>integrateParts({target:root}),/cannot contain repository/);
 const forged=path.join(temp,'forged-evidence.json');fs.writeFileSync(forged,JSON.stringify({...e,checkedAt:'2026-10-08'}));failure('Altered evidence cannot self-certify',()=>integrateParts({target,evidenceFile:forged}),/Unapproved evidence/);
 const baseline=JSON.parse(fs.readFileSync(baselinePath));baseline.fileSha256['src/app.js']='0'.repeat(64);const forgedBaseline=path.join(temp,'forged-baseline.json');fs.writeFileSync(forgedBaseline,JSON.stringify(baseline));failure('Altered lock cannot relabel modified code',()=>integrateParts({target,baselineFile:forgedBaseline}),/Unapproved baseline/);
 const conflict=path.join(target,'src/data/brand-products.js'),beforeConflict=fs.readFileSync(conflict);fs.appendFileSync(conflict,'\n// preserve competing work\n');const conflictTree=snapshot(target);assert.throws(()=>integrateParts({target}),/Checkpoint conflict/);assert.deepEqual(snapshot(target),conflictTree);fs.writeFileSync(conflict,beforeConflict);negative++;
 failure('Injected staging write rolls back',()=>integrateParts({target,transactionFs:{...fs,writeFileSync(){throw Error('Injected write error');}}}),/Injected write error/);
 let renames=0;failure('Commit rename failure restores original',()=>integrateParts({target,transactionFs:{...fs,renameSync(a,b){if(++renames===2)throw Error('Injected rename error');fs.renameSync(a,b);}}}),/Injected rename error/);
 const concurrent=path.join(target,'concurrent-change.txt');assert.throws(()=>integrateParts({target,transactionFs:{...fs,cpSync(a,b,o){fs.cpSync(a,b,o);fs.writeFileSync(concurrent,'preserve concurrent work');}}}),/Concurrent target conflict/);assert.equal(fs.readFileSync(concurrent,'utf8'),'preserve concurrent work');fs.unlinkSync(concurrent);assert.deepEqual(snapshot(target),initial);negative++;
 const link=path.join(target,'unapproved-link');fs.symlinkSync('src/data/catalog.js',link);assert.throws(()=>integrateParts({target}),/Symlink/);fs.unlinkSync(link);negative++;
 const alias=path.join(temp,'symlink-parent');fs.symlinkSync(target,alias,'dir');assert.throws(()=>integrateParts({target:alias}),/Symlink/);fs.unlinkSync(alias);negative++;
 const collision=path.join(target,'src/data/parts-fitment-wave3.js');fs.writeFileSync(collision,'preserve this file');assert.throws(()=>integrateParts({target}),/collision/);assert.equal(fs.readFileSync(collision,'utf8'),'preserve this file');fs.unlinkSync(collision);negative++;
 const bin=path.join(temp,'bin');fs.mkdirSync(bin);fs.writeFileSync(path.join(bin,'git'),"#!/bin/sh\nprintf '%s\\n' main\n",{mode:0o755});failure('No action outside authorized branch',()=>execFileSync(process.execPath,[path.join(root,'integrations/import-parts-fitment-wave3-oem.mjs'),'--target',target],{env:{...process.env,PATH:bin+path.delimiter+process.env.PATH},stdio:'pipe'}),/Only work\/parts-fitment-wave3/);
 const result=integrateParts({target});assert.equal(result.newArticles,21);assert.equal(result.newRelationships,36);
 const once=snapshot(target);assert.equal(integrateParts({target}).state,'already-integrated');assert.equal(integrateParts({target,check:true}).state,'already-integrated');assert.deepEqual(snapshot(target),once,'Replay and --check are read-only');
 const target2=path.join(temp,'second');restore(target2);integrateParts({target:target2});assert.deepEqual(snapshot(target2),once,'Two fresh imports are byte-identical');
 execFileSync(process.execPath,[path.join(target,'tests/parts-fitment-wave3.test.mjs')],{env:{...process.env,UF_PARTS_WAVE3_BASELINE:baselinePath},stdio:'pipe'});
 fs.appendFileSync(path.join(target,'src/data/parts-fitment-wave3.js'),'\n// preserve post-import change');const changed=snapshot(target);assert.throws(()=>integrateParts({target,check:true}),/Integrated output conflict/);assert.deepEqual(snapshot(target),changed);negative++;
 console.log(JSON.stringify({passed:true,negativeCases:negative,newArticles:21,newRelationships:36,freshCheck:'read-only',freshReplay:'byte-identical',idempotent:true,rollback:true,allLegacyArticlesAndFitmentsPreserved:true}));
}finally{fs.rmSync(temp,{recursive:true,force:true});}
