import {routes,legalRoute,readiness} from './readiness.mjs';
const content=Object.freeze({
 'legal-impressum':{title:'Impressum · Veröffentlichung gesperrt',body:'<p class="blocker">P0 · Verifizierte Betreiberangaben fehlen.</p><p>Hier steht kein gültiges Impressum. Betreiber, Rechtsform, Kontakt und gegebenenfalls Register-/ID-Angaben müssen außerhalb des Repositorys geklärt und fachlich geprüft werden. Diese lokale Navigation ist keine öffentliche Veröffentlichung.</p>'},
 'legal-datenschutz':{title:'Datenschutz · lokale technische Hinweise',body:'<p class="blocker">P0 · Keine vollständige Art.-13-Information, keine Datenschutzfreigabe.</p><h3>Auf diesem Gerät</h3><p>Diese Loopback-Preview speichert nur synthetische Missionen mit Geräteauswahl, Variantenangabe, Schritt und Prüfliste im Local Storage dieses Browserprofils. Die beiden Datenmodi bleiben getrennt. Keine Namen, Seriennummern, Adressen oder Kontaktdaten eingeben. Local Storage ist keine verschlüsselte Datensicherung; andere Personen mit Zugriff auf das Profil können ihn lesen. Es gibt hier keine Anmeldung, Analyse-SDKs, Bildabrufe, Händler-API oder Cloud-Uploads.</p><h3>Offline-Vorschau</h3><p>Erst „Offline-Vorschau speichern“ installiert den eigenen Service Worker und speichert nur ausdrücklich erlaubte lokale App-Dateien in CacheStorage. Keine Missionsantworten, Variantenangaben, API- oder Fremdantworten werden gecacht. Die lokale Vorschau verwendet keine Cookies oder Einwilligungsbanner. Dies ist keine rechtliche Erforderlichkeitsentscheidung: Zwecke und mögliche Einwilligung für eine spätere Veröffentlichung bleiben zu prüfen.</p><h3>Prüfpass und Downloads</h3><p>Ein Export wird auf Wunsch als Datei auf diesem Gerät erzeugt, ohne Upload. Heruntergeladene Dateien, Sicherungen, Kopien und die Zwischenablage bleiben auch nach dem App-Löschen erhalten. Sie können Variantenangaben enthalten. Dateien selbst im Downloadordner und gegebenenfalls Backups löschen. Ein Prüfpass ist weder OEM-Signatur noch Einbau-, Kauf- oder Rechtsfreigabe.</p><h3>Was extern gesondert zu prüfen ist</h3><p>Diese Preview startet nur auf Loopback; auch dort gibt es technische Browser-/Serverkommunikation, aber keinen persistenten Serverlog in diesem Testserver. Bei späterem Hosting müssen Verantwortlicher, Empfänger, IP-/Zugriffslogs, Zwecke, Rechtsgrundlagen, DPA, Transfers, Speicherfristen und Betroffenenkontakt tatsächlich geklärt werden. In der älteren App vorhandenes Auth/Edge/Quota und externe Hersteller-/Bild-/Suchlinks sind hier nicht aktiviert. Deren Konten, Sessions und Logs werden durch diesen lokalen Button nicht gelöscht. Affiliate-Tracking und B2B-Mandantendaten erfordern eigene Abnahme.</p>'},
 'legal-kontakt':{title:'Kontakt · Kanal noch offen',body:'<p class="blocker">P0 · Kein verifizierter Betreiber-/Rechtekontakt verfügbar.</p><p>Kein Kontaktformular, Mailversand oder Platzhalter-Mail-Link ist angeschlossen. Bitte keine persönlichen Daten in diese Preview oder GitHub-Issues eintragen. Ein echter Betreiber-/Datenschutzkontakt wird nach privater Klärung und Review vom Owner integriert.</p>'},
 'legal-daten':{title:'Daten & Cache löschen',body:'<p>„Alles lokal löschen“ entfernt beide Missionsmodi dieser Preview und die eigenen Offline-Caches. Der zugehörige Service Worker wird abgemeldet, der In-Memory-Zustand zurückgesetzt und andere geöffnete Preview-Tabs werden zum Zurücksetzen benachrichtigt. Andere Apps, deren Speicher/Caches, Downloads, Zwischenablage, Browser-Verlauf und externe Konten/Logs bleiben erhalten. Abgemeldete Worker können eine bereits geöffnete Seite bis zum nächsten Online-Neustart noch kontrollieren.</p><p>Bei Speicher- oder Browserfehlern wird nur ein Teilergebnis angezeigt, niemals eine vollständige Löschung behauptet. Offline ist nach dem Entfernen der App-Dateien kein Neustart mehr zugesichert. Die Offline-Vorschau wird nicht automatisch neu installiert.</p><form id="erase-form"><label class="confirm"><input id="erase-confirm" type="checkbox" required> Ich möchte beide lokalen Missionsmodi und die Offline-Dateien dieser Preview löschen. Externe Daten und Downloads bleiben bestehen.</label><button id="erase-all" type="submit">Alles lokal löschen</button></form><p id="erase-status" role="status" aria-live="polite"></p>'}
});
// Framework-free injection seam. No owner facts / HTML supplied by a caller.
export function mountLegalNavigation({document,window,navHost,contentHost,onErase,mode='free-readonly'}){
 const nav=document.createElement('nav');nav.dataset.ufLegal='nav';contentHost.dataset.ufLegal='panels';nav.setAttribute('aria-label','Recht, Datenschutz und lokale Daten');
 for(const route of routes){const a=document.createElement('a');a.href='#'+route.id;a.textContent=route.label;nav.append(a);}
 navHost.replaceChildren(nav);
 for(const route of routes){const section=document.createElement('section');section.id=route.id;section.hidden=true;section.className='legal-panel';section.tabIndex=-1;section.setAttribute('aria-labelledby',route.id+'-title');const h=document.createElement('h2');h.id=route.id+'-title';h.textContent=content[route.id].title;section.append(h);const body=document.createElement('div');body.innerHTML=content[route.id].body;section.append(body);contentHost.append(section);}
 const activate=(focus=true)=>{const id=legalRoute(window.location.hash);for(const route of routes){document.getElementById(route.id).hidden=route.id!==id;const link=nav.querySelector(`a[href="#${route.id}"]`);if(route.id===id)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current');}
  contentHost.hidden=!id;if(id&&focus)document.getElementById(id).focus({preventScroll:false});
 };
 const navigate=e=>{const a=e.target.closest('a');if(!a||e.button!==0||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();if(a.hash!==window.location.hash)window.history.pushState(null,'',a.hash);window.dispatchEvent(new window.Event('hashchange'));activate();};
 nav.addEventListener('click',navigate);window.addEventListener('hashchange',activate);activate(false);
 const form=document.getElementById('erase-form');
 const submit=async e=>{e.preventDefault();if(!form.reportValidity())return;const button=document.getElementById('erase-all'),status=document.getElementById('erase-status');button.disabled=true;status.textContent='Lokale Löschung wird geprüft …';
  try{const result=await onErase();status.textContent=result.status==='PASS'?'Ausgewiesener lokaler Speicher und Offline-Dateien entfernt. Downloads und externe Daten bleiben erhalten.':'Löschung nur teilweise verifiziert. Bitte Browser-Speicher prüfen; keine externe Datenlöschung erfolgt.';}catch{status.textContent='Löschung nicht verifiziert. Bitte Browser-Speicher prüfen.';}
  finally{button.disabled=false;document.getElementById('erase-confirm').checked=false;}
 };
 form.addEventListener('submit',submit);
 return {readiness:()=>readiness(mode),setMode(value){mode=readiness(value).mode;},destroy(){window.removeEventListener('hashchange',activate);nav.removeEventListener('click',navigate);form.removeEventListener('submit',submit);nav.remove();contentHost.replaceChildren();}};
}
