import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import {createRequire} from 'node:module';
import {createPreviewServer} from '../../consumer-repair-mission-poc/serve.mjs';
import {catalogSnapshot} from '../../consumer-repair-mission-poc/catalog-snapshot.mjs';
import {cacheName,catalogFingerprint,assetPaths} from '../../consumer-repair-mission-poc/offline-config.mjs';
import {loadPilot,project} from '../project.mjs';
const require=createRequire(import.meta.url),pw=process.env.UF_PLAYWRIGHT_MODULE?await import(process.env.UF_PLAYWRIGHT_MODULE):require('playwright');
const output=path.resolve(process.env.UF_WAVE7_QA_DIR||'/tmp/uf-wave7-qa');await fs.mkdir(output,{recursive:true});
const p=loadPilot(),results=[],errors=[],externalRequests=[],measurements=[],server=createPreviewServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base='http://127.0.0.1:'+server.address().port+'/';const oldFingerprint='a20b269f32838c739a80a60c3d88ebc667e438624a32a9ce2c204768a908f33d:consumer-ui/2';let browser;
const check=async(name,run)=>{await run();results.push(name);console.log('PASS '+name);};
async function fresh(page){await page.goto(base);await page.evaluate(()=>localStorage.clear());await page.reload();await page.locator('#deviceQuery').waitFor();}
async function layout(page){const m=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,clipped:[...document.querySelectorAll('main button,main input,main .source-box,main .device-pass,main .assessment-card,main summary')].filter(e=>{const r=e.getBoundingClientRect();return e.checkVisibility()&&r.width>0&&(r.left< -1||r.right>innerWidth+1||e.scrollWidth>e.clientWidth+2);}).map(e=>e.id||e.className)}));assert.ok(m.scroll<=m.width+1,JSON.stringify(m));assert.deepEqual(m.clipped,[],JSON.stringify(m));return m;}
async function choose(page,a){await page.locator('main [data-step="3"]').click();const group=page.locator('[data-group="'+a+'"]');if(!await group.evaluate(e=>e.open))await group.locator(':scope > summary').click();await page.locator('[data-assembly="'+a+'"]').click();await page.locator('main [data-step="4"]').click();assert.equal(await page.locator('.assessment-card').getAttribute('data-status'),'unclear');assert.match(await page.locator('#assessmentTitle').innerText(),/noch nicht geprüft/);assert.equal(await page.locator('button').filter({hasText:/Kaufen|Bestellen|Warenkorb/}).count(),0);}
try{
 browser=await pw.chromium.launch({headless:true,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage'],...(process.env.UF_CHROMIUM_EXECUTABLE?{executablePath:process.env.UF_CHROMIUM_EXECUTABLE}:{})});
 const ctx=await browser.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true,serviceWorkers:'block'});ctx.on('request',r=>{if(new URL(r.url()).origin!==new URL(base).origin)externalRequests.push(r.url());});
 const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(12000);
 await check('actual Consumer 29 devices, 8 brands, accurate data-bound counts',async()=>{await fresh(page);assert.equal(await page.locator('[data-device]').count(),29);assert.equal(await page.locator('#brandFilter option').count(),9);assert.match(await page.locator('.catalog-note').innerText(),/29 echte Pilotgeräte.*8 Marken.*Snapshot v2/);for(const brand of [...new Set(p.devices.map(d=>d.brand))]){await page.locator('#brandFilter').selectOption({label:brand});assert.equal(await page.locator('[data-device]').count(),catalogSnapshot.devices.filter(d=>d.brand===brand).length);}});
 for(const width of [320,375,390,430])await check(width+'px: all 18 exact new variants through five steps, no real positive',async()=>{
  await page.setViewportSize({width,height:844});for(const d of p.devices){const start=performance.now();await fresh(page);await page.locator('#deviceQuery').fill(d.reference);assert.equal(await page.locator('[data-device]').count(),1);await page.locator('[data-device="'+d.id+'"]').click();await layout(page);await page.locator('main [data-step="2"]').click();await layout(page);assert.match(await page.locator('.source-box').innerText(),/Quellenwebsite DE/);await page.locator('input[value=known]').check();await page.locator('#observedCode').fill(d.reference);
   const part=p.parts.find(a=>d.candidatePartIds.includes(a.id)),a=part?.assembly==='battery'?'battery':part?.assembly==='mechanical'?'body':'filter';
   // Also measure the actual grouped/filtered assembly step before assessment.
   await page.locator('main [data-step="3"]').click();await layout(page);await page.locator('#progress [data-step="2"]').click();await choose(page,a);await layout(page);
   if(!d.candidatePartIds.length){assert.equal(await page.locator('[data-part]').count(),0);assert.match(await page.locator('.empty').innerText(),/keinen dokumentierten Artikel/);}else{assert.ok(await page.locator('[data-part]').count()>0);await page.locator('[data-part]').first().check();assert.match(await page.locator('.candidate').first().innerText(),/Passung unbestätigt/);}
   await page.locator('main [data-step="5"]').click();await layout(page);assert.match(await page.locator('.check-summary').innerText(),/Passung bleibt unbestätigt/);measurements.push({width,deviceId:d.id,reference:d.reference,result:'unclear',purchaseActions:0,elapsedMs:Math.round(performance.now()-start)});
  }await page.screenshot({path:path.join(output,'new-pilot-'+width+'.png'),fullPage:true});
 });
 await check('literal fresh OEM article filter and checklist retain exact 11639250 without approval',async()=>{await fresh(page);await page.locator('#deviceQuery').fill('11602450');await page.locator('[data-device]').click();await page.locator('main [data-step="2"]').click();await page.locator('main [data-step="3"]').click();await page.locator('#partFilterOptions > summary').click();await page.locator('#partQuery').fill('11639250');assert.equal(await page.locator('[data-candidate]').count(),1);assert.match(await page.locator('[data-candidate]').innerText(),/CX FSF.*11639250.*Passung unbestätigt/s);await page.locator('[data-assembly=filter]').click();await page.locator('main [data-step="4"]').click();await page.locator('[data-part="wave7-miele-part-11639250"]').check();await page.locator('main [data-step="5"]').click();assert.match(await page.locator('#section-parts').locator('..').innerText(),/11639250/);});
 await check('market/index/reference mismatch and VK200 sibling never transfer parts or approve',async()=>{await fresh(page);for(const query of ['VS06A110/99','VS20C85G4PB/WA','90025863801']){await page.locator('#deviceQuery').fill(query);assert.equal(await page.locator('[data-device]').count(),0);assert.match(await page.locator('.empty').innerText(),/29 Pilotgeräten nicht erfasst/);}await page.locator('#deviceQuery').fill('VS06A110/03');await page.locator('[data-device]').click();await page.locator('main [data-step="2"]').click();await page.locator('input[value=known]').check();await page.locator('#observedCode').fill('VS06A110/12');assert.match(await page.locator('#variantMismatch').innerText(),/weicht/);await choose(page,'body');assert.match(await page.locator('.missing-list').innerText(),/weicht/);await fresh(page);await page.locator('#deviceQuery').fill('VK200');await page.locator('[data-device]').click();await page.locator('main [data-step="2"]').click();await choose(page,'filter');assert.equal(await page.locator('[data-part]').count(),0);});
 await check('actual old fingerprint actively overwritten; retained old ID, selections, checklist cleared',async()=>{assert.notEqual(catalogFingerprint,oldFingerprint);await fresh(page);await page.evaluate(fingerprint=>localStorage.setItem('uf-repair-mission-poc-v1-real',JSON.stringify({version:2,fingerprint,mode:'real',step:5,deviceId:'vac-miele-model-11806000',problemId:'part',scenarioId:'filter-positive',variantKnown:true,observedCode:'11806000',assemblyId:'filter',selectedPartIds:['miele-part-13070280'],done:['identity']})),oldFingerprint);await page.reload();assert.equal(await page.locator('#deviceQuery').count(),1);assert.equal(await page.locator('[data-device][aria-pressed=true]').count(),0);const raw=await page.evaluate(()=>JSON.parse(localStorage.getItem('uf-repair-mission-poc-v1-real')));assert.equal(raw.fingerprint,catalogFingerprint);assert.equal(raw.deviceId,null);assert.deepEqual(raw.selectedPartIds,[]);assert.deepEqual(raw.done,[]);});
 await check('warm offline reload keeps NEW variant, cached fresh snapshot, unconfirmed checklist',async()=>{const warm=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,serviceWorkers:'allow'}),q=await warm.newPage();q.on('pageerror',e=>errors.push(e.message));warm.on('request',r=>{if(new URL(r.url()).origin!==new URL(base).origin)externalRequests.push(r.url());});try{await fresh(q);await q.waitForFunction(()=>!!navigator.serviceWorker.controller);await q.waitForFunction(()=>document.querySelector('#connectionStatus').textContent.includes('gespeichert'));await q.locator('#deviceQuery').fill('11602450');await q.locator('[data-device]').click();await q.locator('main [data-step="2"]').click();await choose(q,'filter');await q.locator('[data-part]').first().check();await q.locator('main [data-step="5"]').click();const cached=await q.evaluate(async name=>(await(await caches.open(name)).keys()).map(r=>new URL(r.url).pathname),cacheName);assert.deepEqual(cached.sort(),[...assetPaths].sort());await q.addInitScript(()=>Object.defineProperty(navigator,'onLine',{configurable:true,get:()=>false}));await warm.setOffline(true);await q.reload({waitUntil:'domcontentloaded'});assert.match(await q.locator('.device-pass').innerText(),/11602450/);assert.match(await q.locator('.check-summary').innerText(),/Passung bleibt unbestätigt/);assert.match(await q.locator('#connectionStatus').innerText(),/Offline/);
   // connect-src 'none' intentionally blocks fetch. Read already cached bytes.
   const data=await q.evaluate(async name=>{const r=await(await caches.open(name)).match('/catalog-snapshot.mjs');const text=await r.text();return {fresh:text.includes('wave7-de-2026-10-10-v1'),selected:text.includes('11602450')};},cacheName);assert.deepEqual(data,{fresh:true,selected:true});await layout(q);
  }finally{await warm.close();}});
 await check('cold offline with no installation gives network error, no catalog or approvals',async()=>{const cold=await browser.newContext({serviceWorkers:'allow'}),q=await cold.newPage();await cold.setOffline(true);try{await assert.rejects(q.goto(base),/ERR_INTERNET_DISCONNECTED/);assert.equal(await q.locator('[data-device]').count(),0);assert.equal(await q.locator('[data-status=supported]').count(),0);}finally{await cold.close();}});
 assert.deepEqual(errors,[]);assert.deepEqual(externalRequests,[]);assert.equal(measurements.length,72);
 const report={schema:'uf.wave7-browser-report/1',testedAt:new Date().toISOString(),engine:'Chromium headless',version:browser.version(),passed:results.length,checks:results,viewports:[320,375,390,430],newVariantViewportRuns:measurements.length,measuredCoverage:project().counts,measurements,errors,externalRequests,oldFingerprint,newFingerprint:catalogFingerprint,warmOffline:true,coldOfflineNoInstall:'network error, no catalog rendered',physicalPhone:false,safariWebkit:false,externalParticipants:0};await fs.writeFile(path.join(output,'browser-results.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:results.length,newVariantViewportRuns:measurements.length,version:browser.version(),errors:errors.length,externalRequests:externalRequests.length}));
}finally{await browser?.close();await new Promise(r=>server.close(r));}
