import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {loadPilot,loadBaseline,project,outputs,sha} from '../project.mjs';
import {catalogSnapshot} from '../../consumer-repair-mission-poc/catalog-snapshot.mjs';
import {catalogFingerprint} from '../../consumer-repair-mission-poc/offline-config.mjs';
import {offlineConfig} from '../../consumer-repair-mission-poc/prepare-offline.mjs';
import {freshMission,searchDevices,transition,restoreMission,loadMission,assessment,candidateParts,buildRepairPassport} from '../../consumer-repair-mission-poc/mission-state.mjs';
import {browseParts,sourceRegion} from '../../consumer-repair-mission-poc/parts-view.mjs';
const p=loadPilot(),b=loadBaseline();const real=(id,a='filter')=>transition(transition(freshMission(),{type:'device',value:id}),{type:'assembly',value:a});
test('measured actual Consumer 11+18=29, all baseline objects and IDs unchanged, 11+11=22 parts',()=>{assert.deepEqual(project().snapshot,catalogSnapshot);assert.deepEqual(catalogSnapshot.devices.slice(0,11),b.snapshot.devices);assert.deepEqual(catalogSnapshot.parts.slice(0,11),b.snapshot.parts);assert.equal(catalogSnapshot.devices.length,29);assert.equal(catalogSnapshot.parts.length,22);assert.equal(project().counts.additionalBrands,7);assert.equal(project().counts.newDevicePartListings,14);assert.equal(project().counts.newDevicesWithNoSelectedParts,8);assert.equal(catalogSnapshot.wave3Integrated,false);assert.equal(catalogSnapshot.engineIntegrated,false);});
test('all full indexed variants resolve independently, no country/index/PNC/sku substitution',()=>{for(const d of p.devices){assert.equal(searchDevices(d.reference,d.brand).length,1);assert.equal(searchDevices(d.reference,d.brand)[0].id,d.id);}for(const code of ['VS06A110/99','VS20C85G4PB/WA','90025863801','227312-99'])assert.equal(searchDevices(code).length,0);assert.equal(searchDevices('VS06A110').length,2);assert.equal(searchDevices('SNCF0').length,2);assert.equal(freshMission().deviceId,null);});
test('all 18 real devices, five assemblies, correct and incorrect observed codes remain unconfirmed',()=>{for(const d of p.devices)for(const a of ['filter','brush','battery','hose','body'])for(const code of [d.reference,d.reference+'-WRONG']){const s=transition(real(d.id,a),{type:'variant',known:true,code});const v=assessment(s);assert.equal(v.status,'unclear');assert.equal(v.purchaseAllowed,false);assert.equal(v.completeKit,false);if(code!==d.reference)assert.ok(v.missing.some(t=>t.includes('weicht')));const pp=buildRepairPassport(s);assert.equal(pp.verdict.status,'unconfirmed');assert.equal(pp.provenance.freshPilotRelease,p.release);assert.equal(pp.provenance.freshPilotManifestSha256,catalogSnapshot.freshPilot.manifestSha256);}});
test('eight identity-only devices have honest empty part groups, not not-sold claims',()=>{for(const d of p.devices.filter(d=>!d.candidatePartIds.length))for(const a of ['filter','brush','battery','hose','body']){const s=real(d.id,a);assert.deepEqual(candidateParts(s),[]);assert.equal(browseParts(s).groups.find(g=>g.id===a).emptyReason,'not-documented');}});
test('each OEM identity has a separate exact device/assembly listing and remains a literal unconfirmed filter candidate',()=>{for(const l of p.listings){const part=p.parts.find(x=>x.id===l.partId),a=part.assembly==='battery'?'battery':part.assembly==='mechanical'?'body':'filter',s=real(l.deviceId,a);assert.ok(candidateParts(s).some(x=>x.id===part.id));const view=browseParts(s,{query:part.code});assert.equal(view.visibleCount,1);assert.equal(view.groups.reduce((n,g)=>n+g.confirmedReal,0),0);const pp=buildRepairPassport(transition(s,{type:'part',value:part.id}));assert.equal(pp.repair.candidateParts[0].physicalFitApproved,false);assert.equal(pp.repair.candidateParts[0].installationFitment,'unconfirmed');}});
test('same family never transfers /03 wheel to /12, VK7 filters to VK200 or V8 battery to V11',()=>{assert.equal(browseParts(real('vac-wave7-siemens-vs06a110-12','body')).candidates,0);assert.equal(browseParts(real('vac-wave7-vorwerk-vk200')).candidates,0);const s=real('vac-wave7-dyson-268700-01','battery');assert.equal(candidateParts(s).some(x=>x.code==='967834-07'),false);assert.deepEqual(transition(s,{type:'part',value:'wave7-dyson-part-967834-07'}).selectedPartIds,[]);});
test('every fresh source is DE, restricted research not a commercial licence',()=>{for(const x of [...catalogSnapshot.devices,...catalogSnapshot.parts].filter(x=>x.provenance===p.release)){assert.equal(sourceRegion(x.source),'DE');assert.equal(x.source.usageRights.b2cCommercial,'unknown');assert.match(x.source.auditSha256,/^[a-f0-9]{64}$/);}});
test('new lock and offline fingerprint are bound to deterministic generated Consumer bytes',()=>{for(const [name,text] of Object.entries(outputs())){const file=name==='coverage-wave7.json'?'../'+name:'../../consumer-repair-mission-poc/'+name;assert.equal(fs.readFileSync(new URL(file,import.meta.url),'utf8'),text);}const lock=JSON.parse(outputs()['catalog-lock.json']);assert.equal(lock.snapshotSha256,sha(outputs()['catalog-snapshot.mjs']));assert.equal(lock.baselineSnapshotSha256,b.lock.snapshotSha256);assert.equal(catalogFingerprint,offlineConfig().catalogFingerprint);});
test('actual old fingerprint actively clears persisted mission, selections and checklist even for retained IDs',()=>{const old={...real(b.snapshot.devices[0].id),step:5,fingerprint:'a20b269f32838c739a80a60c3d88ebc667e438624a32a9ce2c204768a908f33d:consumer-ui/2',selectedPartIds:['miele-part-13070280'],done:['identity']};assert.deepEqual(restoreMission(old),freshMission());let raw=JSON.stringify(old);const storage={getItem:()=>raw,setItem:(key,value)=>raw=value};assert.deepEqual(loadMission(storage),freshMission());assert.deepEqual(JSON.parse(raw),freshMission());assert.deepEqual(loadMission({...storage,setItem:()=>{throw Error('blocked');}}),freshMission());const s=real(p.devices[0].id);assert.deepEqual(restoreMission(s),s);});
const mutations=[
 ['duplicate full device',p=>p.devices.push(structuredClone(p.devices[0]))],['duplicate stable ID',p=>p.devices[1].id=p.devices[0].id],['duplicate OEM part',p=>p.parts.push(structuredClone(p.parts[0]))],
 ['leading zero removed',p=>{const a=p.parts.find(a=>a.brand==='Siemens');a.code='27606';a.identifiers[0].value=a.code;}],
 ['short PNC',p=>p.devices.find(d=>d.brand==='AEG').reference='900258638'],['dropped E-Nr index',p=>p.devices.find(d=>d.brand==='Siemens').reference='VS06A110'],['different country',p=>p.devices.find(d=>d.brand==='Samsung').reference='VS20C85G4PB/WA'],
 ['third party source',p=>p.sources[0].url='https://example.com/fake'],['third party redirect',p=>p.sources[0].finalUrl='https://example.com/fake'],['invalid hash',p=>p.sources[0].sha256='invalid'],['invented licence',p=>p.sources[0].rights.b2cCommercial='approved'],['wrong market',p=>p.devices[0].market='US'],
 ['another manufacturer source',p=>p.devices[0].identityEvidence=p.devices.find(d=>d.brand==='Dyson').identityEvidence],['missing OEM proof',p=>p.parts[0].identityEvidence.sourceId='absent'],['candidate without listing',p=>p.devices.find(d=>!d.candidatePartIds.length).candidatePartIds.push(p.parts[0].id)],['removed scoped listing',p=>p.listings.pop()],
 ['positive promotion',p=>p.listings[0].status='confirmed'],['purchase allowed',p=>p.listings[0].purchaseAllowed=true],['connector approval',p=>p.listings[0].physicalFitApproved=true],['wrong assembly',p=>p.listings[0].assembly='battery'],['wrong scope',p=>p.listings[0].deviceReference='OTHER'],['invented price',p=>p.parts[0].price=1]
];for(const [name,mutate] of mutations)test('reject '+name,()=>{const x=structuredClone(p);mutate(x);assert.throws(()=>project(x,b));});
