import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawnSync,execFileSync} from 'node:child_process';
import {root,own,scopeProof} from './scope.mjs';
const dir=path.join(root,own,'artifacts');fs.mkdirSync(dir,{recursive:true});
const testedCommit=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();
const preflight=spawnSync('python3',['integrations/consumer-launch-preflight-wave6/preflight.py','--receipts','integrations/consumer-launch-preflight-wave6/receipts.example.json','--json'],{cwd:root,encoding:'utf8',maxBuffer:4*1024*1024});
assert.equal(preflight.status,2,'Must remain legal/source BLOCKED');const legal=JSON.parse(preflight.stdout);
assert.equal(legal.launchApproved,false);assert.equal(legal.overall,'BLOCKED');assert.notEqual(legal.checks.find(x=>x.id==='source-identity').status,'PASS');
fs.writeFileSync(path.join(dir,'preflight-blocked.json'),JSON.stringify(legal,null,2)+'\n');
const scorecard=JSON.parse(execFileSync('node',['integrations/private-owner-wave5/catalog-scorecard.mjs'],{cwd:root,encoding:'utf8'}));
assert.equal(scorecard.counts.devices,11);assert.equal(scorecard.counts.brands,5);assert.equal(scorecard.fitment.approvedRealInstallationCases,0);
fs.writeFileSync(path.join(dir,'owner-scorecard.json'),JSON.stringify(scorecard,null,2)+'\n');
const browser=JSON.parse(fs.readFileSync(path.join(root,'integrations/private-owner-wave5/artifacts/owner-integration-browser/results.json'),'utf8'));
assert.equal(browser.expected,66);assert.equal(browser.passed,66);assert.equal(browser.failed,0);assert.equal(browser.complete,true);assert.equal(browser.cases.length,66);
const discovery=JSON.parse(fs.readFileSync(path.join(dir,'discovery-results.json'),'utf8'));assert.equal(discovery.passed,32);assert.equal(discovery.testedCommit,testedCommit);
const report={schema:'uf.discovery-owner-acceptance/1',testedCommit,sourceDelta:scopeProof(),browser,discovery,scorecard,preflight:{overall:legal.overall,launchApproved:legal.launchApproved,sourceIdentity:legal.checks.find(x=>x.id==='source-identity')},physicalIPhone:false,humanPilot:false,launchApproved:false};
fs.writeFileSync(path.join(dir,'acceptance.json'),JSON.stringify(report,null,2)+'\n');console.log('WAVE9-REPORT-PROOF '+JSON.stringify(report));
