import test from 'node:test';
import assert from 'node:assert/strict';
import {performance} from 'node:perf_hooks';
import {createHash} from 'node:crypto';
import {catalogSnapshot} from '../consumer-repair-mission-poc/catalog-snapshot.mjs';
import {generateSyntheticFixtures} from './fixtures.mjs';
import {manifest,validateBatch,checkCandidate,keyOf,stageFromEvidence,simulateEvidenceStages,ingestSynthetic,batchReport,markdown} from './ingest.mjs';
const cp=x=>structuredClone(x);
const fail=f=>{const d=cp(manifest);f(d);return ()=>validateBatch(d,catalogSnapshot)};
const by=(d,brand)=>d.realRecords.find(x=>x.brand===brand);
test('37 exact official candidate observations, 11 real Consumer devices preserved',()=>{const r=batchReport(manifest,catalogSnapshot);assert.equal(r.research.researched,37);assert.equal(r.research.validated,37);assert.equal(r.consumerBaseline.devices,11);assert.equal(r.consumerBaseline.partIdentities,11);assert.equal(r.research.boschWithoutFullENumber,2);assert.equal(r.research.stages.candidate_observed,37);assert.equal(r.research.independentlySourceVerified,0);assert.equal(r.gates.launchApproved,false)});
test('domain and brand boundaries count without converting fixtures',()=>{const r=batchReport(manifest,catalogSnapshot);assert.equal(r.research.byDomainBrand.reduce((a,x)=>a+x.count,0),37);assert.deepEqual([manifest.realRecords.filter(x=>x.domain==='washing-machine').length,manifest.realRecords.filter(x=>x.domain==='vacuum-cleaner').length],[8,29]);assert.equal(r.synthetic.countedAsReal,false)});
test('variant dedup uses entire market, PNC, full part-number, and SKU',()=>{const a=manifest.realRecords[0],b=cp(a);b.market='GB';assert.notEqual(keyOf(a),keyOf(b));const c=cp(a);c.variant.eNumber='WGG244ZR90/01';assert.notEqual(keyOf(a),keyOf(c));const p=by(manifest,'AEG'),p2=cp(p);p2.variant.pnc='000000001';assert.notEqual(keyOf(p),keyOf(p2));assert.throws(fail(d=>d.realRecords.push(cp(d.realRecords[0]))),/duplicate/i)});
test('same Miele model name with distinct material IDs is retained',()=>{const a=manifest.realRecords.filter(x=>x.brand==='Miele'&&x.model==='Boost CX1 PowerLine');assert.equal(a.length,2);assert.notEqual(a[0].primary.value,a[1].primary.value);assert.notEqual(keyOf(a[0]),keyOf(a[1]))});
test('Bosch bare model never becomes invented E-Nr /xx',()=>{assert.throws(fail(d=>by(d,'Bosch').variant.eNumber='WGG244ZR90/01'),/Bosch full/);assert.throws(fail(d=>by(d,'Bosch').identityStatus='independently_verified'))});
test('AEG PNC with leading zero and exact OEM locator',()=>{assert.throws(fail(d=>by(d,'AEG').variant.pnc='91450082'),/PNC/);assert.throws(fail(d=>by(d,'AEG').source.locator='PNC 914 500 999'),/PNC/);const x=cp(by(manifest,'AEG'));x.variant.pnc='000000001';assert.notEqual(keyOf(x),keyOf(by(manifest,'AEG')))});
test('Hoover 8-digit model code and sibling slug cannot transfer',()=>{assert.throws(fail(d=>by(d,'Hoover').variant.manufacturerProductCode='39401105'),/Hoover/);assert.throws(fail(d=>by(d,'Hoover').primary.value='HF610P 011'),/Hoover/)});
test('Dyson SKU suffix cannot silently change',()=>{assert.throws(fail(d=>by(d,'Dyson').primary.value='394167'),/Dyson/);assert.throws(fail(d=>by(d,'Dyson').primary.value='394167-02'),/Dyson/)});
test('OEM-host, missing URL, source locator, HTTPS and date are mandatory',()=>{for(const m of [d=>d.realRecords[0].source.url='https://fake.invalid/product',d=>d.realRecords[0].source.url='http://www.bosch-home.com/x',d=>d.realRecords[0].source.url='',d=>d.realRecords[0].source.locator='',d=>d.realRecords[0].source.observedAt='never'])assert.throws(fail(m))});
test('exact market and identity names are not auto-translated',()=>{assert.throws(fail(d=>d.realRecords[0].market='GB'),/region/);assert.throws(fail(d=>by(d,'Miele').primary.value='99999999'),/Miele/)});
test('fake raw archive, identity audit, rights, and fitment stage rejected',()=>{for(const mod of [d=>d.realRecords[0].source.originalBytesArchive={sha256:'fake'},d=>d.realRecords[0].source.independentIdentityReview={verified:true},d=>d.realRecords[0].source.rightsReview={approved:true},d=>d.realRecords[0].source.fitmentReview={verified:true},d=>d.realRecords[0].evidenceStage='rights_reviewed'])assert.throws(fail(mod))});
test('media, original parts, physical fits, publication and license cannot appear',()=>{for(const mod of [d=>d.realRecords[0].consumerPublished=true,d=>d.realRecords[0].fitmentConfirmed=true,d=>d.realRecords[0].licenseApproved=true,d=>d.realRecords[0].originalParts.push('fake'),d=>d.realRecords[0].fitmentEdges.push('fake'),d=>d.realRecords[0].positivePhysicalFits=1])assert.throws(fail(mod))});
test('250 synthetic rows, timed processing; 0 extra actual devices',()=>{const synthetic=generateSyntheticFixtures(250),start=performance.now(),r=ingestSynthetic(synthetic),elapsed=performance.now()-start;assert.equal(r.processed,250);assert.equal(r.realCandidatesAdded,0);assert.equal(r.consumerImports,0);assert.ok(elapsed<20000);console.log('PERF 250 synthetic records: '+elapsed.toFixed(3)+' ms; '+Math.round(250000/Math.max(1,elapsed))+' records/s');assert.equal(batchReport(manifest,catalogSnapshot).research.researched,37)});
test('1000 synthetic rows throughput, no real OEM mixing',()=>{const rows=generateSyntheticFixtures(1000),start=performance.now(),r=ingestSynthetic(rows),ms=performance.now()-start;assert.equal(r.processed,1000);assert.ok(ms<20000);console.log('PERF 1000 synthetic records: '+ms.toFixed(3)+' ms');assert.throws(()=>validateBatch({...manifest,realRecords:[...manifest.realRecords,rows[0]]},catalogSnapshot))});
test('synthetic duplicate, swapped test tag, fake source, invented license rejected',()=>{for(const mod of [a=>a.push(cp(a[0])),a=>a[0].recordType='oem_research_candidate',a=>a[0].fixtureOnly=false,a=>a[0].source.url='https://www.miele.de',a=>a[0].licenseApproved=true]){const a=generateSyntheticFixtures(120);mod(a);assert.throws(()=>ingestSynthetic(a))}});
test('minimum synthetic 100 enforced and maximum bounded',()=>{assert.throws(()=>generateSyntheticFixtures(99));assert.throws(()=>generateSyntheticFixtures(20001));assert.equal(ingestSynthetic(generateSyntheticFixtures(100)).processed,100)});
test('real pilot bounded 50, zero hypothetical overfill',()=>{assert.throws(fail(d=>{for(let i=0;i<20;i++){const c=cp(d.realRecords[0]);c.id='W11-9'+i;d.realRecords.push(c)}}),/50-item/)});
test('report JSON and markdown deterministic, launch false',()=>{const a=batchReport(manifest,catalogSnapshot),b=batchReport(manifest,catalogSnapshot);assert.deepEqual(a,b);assert.ok(markdown(a).includes('## Echte und synthetische Counts'));assert.equal(a.gates.consumerPublished,false)});

test('synthetic SHA256 -> independent audit -> rights -> physical review has five distinct stages, never actual approval',()=>{
 const row=manifest.realRecords[0];
 const bytes=Buffer.from('SYNTHETIC_TEST_BYTES_NOT_AN_OEM_ARCHIVE');
 const digest=createHash('sha256').update(bytes).digest('hex');
 const archive={syntheticBytes:bytes,declaredSha256:digest,exactSourceUrl:row.source.url,capturedBy:'fixture-capturer'};
 const base={simulationOnly:true,archive};
 assert.equal(simulateEvidenceStages(row,null).stage,'candidate_observed');
 assert.equal(simulateEvidenceStages(row,base).stage,'original_bytes_archived');
 const independentReview={auditor:'separate-test-reviewer',sha256:digest,exactVariantKey:keyOf(row),identityResult:'verified'};
 assert.equal(simulateEvidenceStages(row,{...base,independentReview}).stage,'identity_independently_verified');
 const rightsReview={contractId:'SYNTHETIC-NOT-A-LEGAL-LICENCE',reviewedBy:'second-test-reviewer',commercialUse:'approved',mediaUse:'approved'};
 assert.equal(simulateEvidenceStages(row,{...base,independentReview,rightsReview}).stage,'rights_reviewed');
 const fitmentReview={physicalTest:'verified',partCode:'SYNTHETIC-PART',serialOrRevisionScope:'SYNTHETIC-SCOPE',safetyReviewer:'test-safety',technicalEvidenceId:'SYNTHETIC-TEST-EVIDENCE'};
 const result=simulateEvidenceStages(row,{...base,independentReview,rightsReview,fitmentReview});
 assert.equal(result.stage,'fitment_verified');assert.equal(result.simulationOnly,true);assert.equal(result.consumerApproved,false);
 assert.equal(row.evidenceStage,'candidate_observed');
 assert.throws(()=>simulateEvidenceStages(row,{...base,archive:{...archive,declaredSha256:'invented'}}),/SHA mismatch/);
 assert.throws(()=>simulateEvidenceStages(row,{...base,independentReview:{...independentReview,auditor:'fixture-capturer'}}),/Independent/);
 assert.throws(()=>simulateEvidenceStages(row,{...base,rightsReview}),/stage skip/);
 assert.throws(()=>simulateEvidenceStages(row,{...base,independentReview,fitmentReview}),/No fitment/);
 assert.throws(()=>simulateEvidenceStages(row,{...base,independentReview,rightsReview,fitmentReview:{...fitmentReview,technicalEvidenceId:''}}),/Physical/);
});
